FROM node:20-alpine

WORKDIR /app

# Otimiza cache
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o restante dos arquivos (mas no dev usaremos bind)
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]